# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: Mesh
metadata:
  name: mesh
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  peering:
    peerThroughMeshGateways: true