# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: database-deny
spec:
  destination:
    name: database
  sources:
   - name: "*"
     action: deny
   - name: application
     action: allow
     peer: dc2 ## The peer of the source service