# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: consul.hashicorp.com/v1alpha1
kind: PeeringDialer
metadata:
  name: SOURCE
spec:
  peer:
    secret:
      name: "peering-token-SOURCE-to-TARGET"
      key: "data"
      backend: "kubernetes"