# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

global:
  name: consul
  datacenter: DATACENTER
  image: hashicorp/consul:1.16.0
  imageK8S: absolutelightning/consul-k8s-argocd:latest

  tls:
    enabled: true

  peering:
    enabled: true

  acls:
    manageSystemACLs: true

  argocd:
    enabled: true

connectInject:
  enabled: true

meshGateway:
  enabled: true