global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.16.0
  imageK8S: absolutelightning/consul-k8s-argocd:latest

  argocd:
    enabled: true 

  tls:
    enabled: true

  peering:
    enabled: true

  acls:
    manageSystemACLs: true

server:
  replicas: 3
  updatePartition: 0

connectInject:
  enabled: true

meshGateway:
  enabled: true
