apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: consul
  source:
    repoURL: 'https://github.com/absolutelightning/consul-minikubes.git'
    targetRevision: test-argocd
    path: argocd/observability
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd