apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: consul
  sources:
    - chart: consul
      repoURL: https://2b1d-2406-7400-98-7d44-fd8b-f686-ea06-d832.ngrok-free.app/
      targetRevision: NET-5229-Create-dedicated-argocd-stanza
      helm:
        releaseName: consul
        valueFiles:
          - $values/argocd/consul-helm-values.yaml
    - repoURL: 'https://github.com/absolutelightning/consul-minikubes.git'
      targetRevision: test-argocd
      ref: values
    - repoURL: 'https://github.com/absolutelightning/consul-minikubes.git'
      path: argocd/consul-config
      targetRevision: test-argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul