apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: consul
  sources:
    - repoURL: 'https://github.com/absolutelightning/consul-minikubes.git'
      path: argocd/jaeger
      targetRevision: test-argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul